packages:
  - client/
  - server/
  - e2e/
allowBuilds:
  bcrypt: true
  core-js: true
  esbuild: true
  negaposi-analyzer-ja: true
  sqlite3: true
overrides:
  gifler>bluebird: 3.7.2
  gifler>omggif: 1.0.10
patchedDependencies:
  kuromoji@0.1.2: patches/kuromoji@0.1.2.patch
saveExact: true
shellEmulator: true
